Products:{
  - filename: "Tomatoes.jpeg"
    dispname: "Tomato"
    price: "R10.00"
  @
  - filename: "Tomatoes.jpeg"
    dispname: "Tomato"
    price: "R10.00"
}
Not-in-stock:{
  - filename: "boerewors.jpeg"
    dispname: "wors"
    price: "R20.00"
}
