Products:
  - filename: "Butternut.jpeg"
    dispname: "Butternut"
    price: "R15.00"
  - filename: "Tomatoes.jpeg"
    dispname: "Tomato"
    price: "R10.00"

Not-in-stock:
  - filename: "boerewors.jpeg"
    dispname: "Wors"
    price: "R20.00"
