Products:
  - filename: "Butternut.jpeg"
    dispname: "Butternut"
    price: "R15.00"
    outofstock: false
    notonsaleyet: true

  - filename: "Tomatoes.jpeg"
    dispname: "Tomato"
    price: "R10.00"
    outofstock: true
    notonsaleyet: false

Not-in-stock:
  - filename: "boerewors.jpeg"
    dispname: "Wors"
    price: "R20.00"
    outofstock: false
    notonsaleyet: false
    
