Products:
  - filename: "9a68938f-4607-4911-afc7-ac03e5fb66f7.jpg"
    dispname: "Jaffels"
    price: "R15.00"

Not-in-stock:
  - filename: ""
    dispname: "Curry mince vetkoek"
    price: "R?"
  - filename: ""
    dispname: "HamBurger"
    price: "R?"
